### ISSUE TITLE
Can't find node_sqlite3.node

### ISSUE THREAD

**Issue by ustroetz** [mapbox/osrm-matching-inspection#4]
I am trying to import traces. The gpx files are in the folder `data`.
If I use  `node bin/server.js data`

I get the following error:

```
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/ustroetz/projects/osrm-matching-inspection/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ustroetz/projects/osrm-matching-inspection/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

The module `node_sqlite3.node` exists under the specified path. What could be the reason for the error?

**Comment by springmeyer** [comment]
Can you remove `./node_modules`, run `npm install` again and watch for any obvious errors? If no errors show up can you let us know if the `bin/server.js` is fixed or still broken?

**Comment by ustroetz** [comment]
Did what you said and `node bin/server.js data` works fine now. Thanks!
